import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { loadPieceSet } from '../styles/pieceSets';

export type BoardTheme = 'brown' | 'blue' | 'green' | 'gray';

/** Piece-set catalogue. Art is generated by scripts/gen-piece-sets.mjs. The
 *  first entry (cburnett) is the default and is bundled eagerly. */
export const PIECE_SETS = [
  { id: 'cburnett', label: 'cburnett' },
  { id: 'merida', label: 'Merida' },
  { id: 'alpha', label: 'Alpha' },
  { id: 'maestro', label: 'Maestro' },
  { id: 'california', label: 'California' },
  { id: 'cardinal', label: 'Cardinal' },
  { id: 'governor', label: 'Governor' },
  { id: 'horsey', label: 'Horsey' },
  { id: 'staunty', label: 'Staunty' },
] as const;

export type PieceSet = (typeof PIECE_SETS)[number]['id'];

interface SettingsState {
  sound: boolean;
  premove: boolean;
  boardTheme: BoardTheme;
  pieceSet: PieceSet;
  setSound(b: boolean): void;
  setPremove(b: boolean): void;
  setBoardTheme(t: BoardTheme): void;
  setPieceSet(p: PieceSet): void;
}

export const useSettings = create<SettingsState>()(
  persist(
    (set) => ({
      sound: true,
      premove: true,
      boardTheme: 'brown',
      pieceSet: 'cburnett',
      setSound: (sound) => set({ sound }),
      setPremove: (premove) => set({ premove }),
      setBoardTheme: (boardTheme) => set({ boardTheme }),
      setPieceSet: (pieceSet) => {
        loadPieceSet(pieceSet);
        set({ pieceSet });
      },
    }),
    {
      name: 'chesser-settings',
      // Eagerly fetch the persisted set's CSS as soon as state rehydrates.
      onRehydrateStorage: () => (state) => {
        if (state?.pieceSet) loadPieceSet(state.pieceSet);
      },
    },
  ),
);
