import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { loadPieceSet } from '../styles/pieceSets';
import { applyTheme, type ThemePref } from '../lib/theme';

export type BoardTheme = 'brown' | 'blue' | 'green' | 'gray' | 'candy' | 'mint';
export type { ThemePref };

/** Piece-set catalogue. Art is generated by scripts/gen-piece-sets.mjs. The
 *  first entry (cburnett) is the default and is bundled eagerly. */
export const PIECE_SETS = [
  { id: 'cburnett', label: 'cburnett' },
  { id: 'merida', label: 'Merida' },
  { id: 'alpha', label: 'Alpha' },
  { id: 'maestro', label: 'Maestro' },
  { id: 'california', label: 'California' },
  { id: 'cardinal', label: 'Cardinal' },
  { id: 'governor', label: 'Governor' },
  { id: 'horsey', label: 'Horsey' },
  { id: 'staunty', label: 'Staunty' },
] as const;

export type PieceSet = (typeof PIECE_SETS)[number]['id'];

/** Which rating meter is shown as the headline number across the app. */
export type RatingMeter = 'elo' | 'glicko';

interface SettingsState {
  sound: boolean;
  premove: boolean;
  arrows: boolean; // draw the engine's best-move arrows on the analysis board
  /** AI Coach prose (LLM-worded engine facts). Degrades gracefully when the
   *  server has no LLM key, so it defaults on; rule-based text always remains. */
  aiCoach: boolean;
  boardTheme: BoardTheme;
  pieceSet: PieceSet;
  ratingMeter: RatingMeter;
  /** App color theme: explicit light/dark, or follow prefers-color-scheme. */
  theme: ThemePref;
  setSound(b: boolean): void;
  setPremove(b: boolean): void;
  setArrows(b: boolean): void;
  setAiCoach(b: boolean): void;
  setBoardTheme(t: BoardTheme): void;
  setPieceSet(p: PieceSet): void;
  setRatingMeter(m: RatingMeter): void;
  setTheme(t: ThemePref): void;
}

export const useSettings = create<SettingsState>()(
  persist(
    (set) => ({
      sound: true,
      premove: true,
      arrows: true,
      aiCoach: true,
      boardTheme: 'brown',
      pieceSet: 'cburnett',
      ratingMeter: 'elo',
      // Dark is the app's historical look; light/system are opt-in.
      // index.html's inline script applies this before first paint.
      theme: 'dark',
      setSound: (sound) => set({ sound }),
      setPremove: (premove) => set({ premove }),
      setArrows: (arrows) => set({ arrows }),
      setAiCoach: (aiCoach) => set({ aiCoach }),
      setBoardTheme: (boardTheme) => set({ boardTheme }),
      setPieceSet: (pieceSet) => {
        loadPieceSet(pieceSet);
        set({ pieceSet });
      },
      setRatingMeter: (ratingMeter) => set({ ratingMeter }),
      setTheme: (theme) => {
        applyTheme(theme);
        set({ theme });
      },
    }),
    {
      name: 'chesser-settings',
      // Eagerly fetch the persisted set's CSS as soon as state rehydrates,
      // and re-assert the theme (covers 'system' listener wiring too).
      onRehydrateStorage: () => (state) => {
        if (state?.pieceSet) loadPieceSet(state.pieceSet);
        applyTheme(state?.theme ?? 'dark');
      },
    },
  ),
);
