export interface OpeningLine {
  id: string;
  name: string;
  eco: string;
  /** The side you train (whose moves you must recall). */
  side: 'white' | 'black';
  /** Main line in SAN from the initial position. */
  moves: string[];
  idea: string;
}

export const OPENING_LINES: OpeningLine[] = [
  // ---- White ----
  {
    id: 'italian',
    name: 'Italian Game — Giuoco Pianissimo',
    eco: 'C50',
    side: 'white',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd3', 'd6', 'O-O', 'O-O'],
    idea: 'Slow build-up: clamp the centre with c3/d3, castle, then expand with Nbd2–f1–g3 and d4.',
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy Lopez — Closed',
    eco: 'C84',
    side: 'white',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O'],
    idea: 'Pressure e5 with Bb5; after a6/b5 retreat to b3 and prepare d4 with c3 and Nbd2.',
  },
  {
    id: 'scotch',
    name: 'Scotch Game',
    eco: 'C45',
    side: 'white',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Bc5', 'Be3', 'Qf6', 'c3', 'Nge7'],
    idea: 'Open the centre early; trade on d4 and develop quickly with a small space edge.',
  },
  {
    id: 'four-knights',
    name: 'Four Knights — Spanish',
    eco: 'C48',
    side: 'white',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6', 'Bb5', 'Bb4', 'O-O', 'O-O', 'd3', 'd6'],
    idea: 'Symmetrical and solid; complete development and look for Bg5, Nd5 or a later break.',
  },
  {
    id: 'vienna',
    name: 'Vienna Game',
    eco: 'C26',
    side: 'white',
    moves: ['e4', 'e5', 'Nc3', 'Nf6', 'g3', 'd5', 'exd5', 'Nxd5', 'Bg2', 'Nxc3', 'bxc3', 'Bc5'],
    idea: 'A flexible King’s-Gambit cousin: fianchetto the bishop and pressure the long diagonal.',
  },
  {
    id: 'qgd',
    name: "Queen's Gambit Declined",
    eco: 'D37',
    side: 'white',
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'Be7', 'Bf4', 'O-O', 'e3', 'c5'],
    idea: 'Classical centre. Develop harmoniously and aim for the minority attack or e4 break.',
  },
  {
    id: 'qga',
    name: "Queen's Gambit Accepted",
    eco: 'D20',
    side: 'white',
    moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'Nf6', 'e3', 'e6', 'Bxc4', 'c5', 'O-O', 'a6'],
    idea: 'Reclaim the pawn with Bxc4, seize the centre, and use the open lines for the pieces.',
  },
  {
    id: 'catalan',
    name: 'Catalan Opening',
    eco: 'E06',
    side: 'white',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'dxc4'],
    idea: 'Fianchetto pressure on d5 and the long diagonal; regain c4 later with lasting bind.',
  },
  {
    id: 'london',
    name: 'London System',
    eco: 'D02',
    side: 'white',
    moves: ['d4', 'd5', 'Nf3', 'Nf6', 'Bf4', 'e6', 'e3', 'c5', 'c3', 'Nc6', 'Nbd2', 'Bd6'],
    idea: 'A solid, easy-to-learn setup: Bf4, e3, c3, Nbd2. Reliable structure against almost anything.',
  },
  {
    id: 'colle',
    name: 'Colle System',
    eco: 'D05',
    side: 'white',
    moves: ['d4', 'd5', 'Nf3', 'Nf6', 'e3', 'e6', 'Bd3', 'c5', 'c3', 'Nc6', 'Nbd2', 'Bd6'],
    idea: 'Build the e3–d4–c3 triangle, then unleash the e4 break for a kingside initiative.',
  },
  {
    id: 'english',
    name: 'English Opening — Reversed Sicilian',
    eco: 'A29',
    side: 'white',
    moves: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6', 'g3', 'd5', 'cxd5', 'Nxd5', 'Bg2', 'Nb6'],
    idea: 'A Sicilian a tempo up: fianchetto, pressure the centre, and play on the queenside.',
  },
  {
    id: 'reti',
    name: 'Réti Opening',
    eco: 'A09',
    side: 'white',
    moves: ['Nf3', 'd5', 'c4', 'd4', 'b4', 'g6', 'Bb2', 'Bg7', 'e3', 'dxe3', 'fxe3', 'c5'],
    idea: 'Hypermodern flank play: undermine Black’s broad centre from the wings.',
  },
  {
    id: 'trompowsky',
    name: 'Trompowsky Attack',
    eco: 'A45',
    side: 'white',
    moves: ['d4', 'Nf6', 'Bg5', 'Ne4', 'Bf4', 'd5', 'e3', 'c5', 'Bd3', 'Nc6', 'c3', 'Qb6'],
    idea: 'Pin the knight early and sidestep heavy theory, steering into your own structures.',
  },

  // ---- Black ----
  {
    id: 'najdorf',
    name: 'Sicilian Defence — Najdorf',
    eco: 'B90',
    side: 'black',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6'],
    idea: 'The sharpest Sicilian. ...a6 prepares ...e5 or ...b5 and keeps maximum flexibility.',
  },
  {
    id: 'dragon',
    name: 'Sicilian Defence — Dragon',
    eco: 'B70',
    side: 'black',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Be2', 'Bg7'],
    idea: 'Fianchetto the dragon bishop and storm the queenside while eyeing the long diagonal.',
  },
  {
    id: 'sveshnikov',
    name: 'Sicilian Defence — Sveshnikov',
    eco: 'B33',
    side: 'black',
    moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5', 'Ndb5', 'd6'],
    idea: 'Accept a backward d-pawn for active piece play and the bishop pair.',
  },
  {
    id: 'taimanov',
    name: 'Sicilian Defence — Taimanov',
    eco: 'B47',
    side: 'black',
    moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4', 'Nc6', 'Nc3', 'Qc7', 'Be2', 'a6'],
    idea: 'Flexible development with ...Qc7 and ...a6; aim for ...Nf6, ...Bb4 or ...b5.',
  },
  {
    id: 'caro-kann',
    name: 'Caro-Kann — Classical',
    eco: 'B18',
    side: 'black',
    moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6', 'h4', 'h6', 'Nf3', 'Nd7'],
    idea: 'Solid and sound: trade the bad bishop early with ...Bf5–g6 and build a sturdy structure.',
  },
  {
    id: 'french-winawer',
    name: 'French Defence — Winawer',
    eco: 'C18',
    side: 'black',
    moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4', 'e5', 'c5', 'a3', 'Bxc3+', 'bxc3', 'Ne7'],
    idea: 'Pin and trade on c3 to wreck White’s queenside pawns, then pressure the centre with ...c5.',
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian Defence',
    eco: 'B01',
    side: 'black',
    moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'd4', 'Nf6', 'Nf3', 'c6', 'Bc4', 'Bf5'],
    idea: 'Trade centre pawns immediately; reroute the queen to a5 and develop classically.',
  },
  {
    id: 'pirc',
    name: 'Pirc Defence',
    eco: 'B07',
    side: 'black',
    moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O', 'O-O', 'c6'],
    idea: 'Concede the centre, then strike it with ...e5 or ...c5 after the kingside is safe.',
  },
  {
    id: 'petroff',
    name: 'Petroff Defence',
    eco: 'C42',
    side: 'black',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4', 'd4', 'd5', 'Bd3', 'Nc6'],
    idea: 'Symmetry and solidity: equalise by mirroring and freeing the pieces.',
  },
  {
    id: 'nimzo-indian',
    name: 'Nimzo-Indian Defence',
    eco: 'E32',
    side: 'black',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2', 'O-O', 'a3', 'Bxc3+', 'Qxc3', 'b6'],
    idea: 'Trade the bishop for the c3-knight to fight for e4 and double White’s pawns.',
  },
  {
    id: 'kings-indian',
    name: "King's Indian Defence",
    eco: 'E92',
    side: 'black',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5'],
    idea: 'Cede the centre, then strike back with ...e5 and a kingside pawn storm.',
  },
  {
    id: 'grunfeld',
    name: 'Grünfeld Defence',
    eco: 'D85',
    side: 'black',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7'],
    idea: 'Invite a big White centre, then chip away at it with pieces and ...c5.',
  },
  {
    id: 'queens-indian',
    name: "Queen's Indian Defence",
    eco: 'E15',
    side: 'black',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Ba6', 'b3', 'Bb4+', 'Bd2', 'Be7'],
    idea: 'Control e4 with the light-squared bishop and a flexible, hypermodern setup.',
  },
  {
    id: 'slav',
    name: 'Slav Defence',
    eco: 'D15',
    side: 'black',
    moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'a4', 'Bf5'],
    idea: "Support d5 with ...c6 keeping the light-squared bishop free; grab c4 and develop ...Bf5.",
  },
  {
    id: 'benoni',
    name: 'Modern Benoni',
    eco: 'A61',
    side: 'black',
    moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6'],
    idea: 'Unbalance with a queenside majority and the long-diagonal bishop for dynamic play.',
  },
];
