// AUTO-GENERATED by scripts/gen-tactics.mjs — verified by Stockfish.
// Each position has a single winning move (the first entry of `solution`).
export type Difficulty = 'easy' | 'medium' | 'hard';
export interface Puzzle {
  id: string;
  fen: string;
  /** UCI moves; solution[0] is the key move, the rest is the main line. */
  solution: string[];
  theme: string;
  difficulty: Difficulty;
  turn: 'white' | 'black';
}

export const PUZZLES: Puzzle[] = [
  {
    "id": "t1",
    "fen": "rnk4r/2pq2pp/1p1bpn2/p5N1/2P4K/P2P3N/1P2P2P/R1BQ4 b - - 4 16",
    "solution": [
      "h7h6",
      "c1f4",
      "h6g5",
      "h4g3",
      "g5f4",
      "g3g2"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "black"
  },
  {
    "id": "t2",
    "fen": "rnbqkbnr/ppppp2p/8/5pp1/4P3/6PB/PPPP1P1P/RNBQK1NR w KQkq - 0 4",
    "solution": [
      "d1h5"
    ],
    "theme": "Mate in 1",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t3",
    "fen": "1rb2knr/3n2p1/4pqQ1/1p4Np/2pP4/2P1B2P/4BPP1/b4RK1 w - - 4 19",
    "solution": [
      "g5e6",
      "f8e7",
      "e3g5",
      "e7e6",
      "g5f6",
      "g8f6"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t4",
    "fen": "1rb3nr/3nk1p1/4NqQ1/1p5p/2pP4/2P1B2P/4BPP1/b4RK1 w - - 1 20",
    "solution": [
      "e3g5",
      "e7e6",
      "g5f6",
      "g8f6",
      "f1a1",
      "e6d6"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t5",
    "fen": "1rb3nr/3n2p1/4kqQ1/1p4Bp/2pP4/2P4P/4BPP1/b4RK1 w - - 0 21",
    "solution": [
      "g5f6"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t6",
    "fen": "1rb3nr/3n2p1/5qQ1/1p1Pk1Bp/2p5/2P4P/4BPP1/b4RK1 w - - 1 22",
    "solution": [
      "g5f6",
      "g8f6",
      "g6g3",
      "e5d5",
      "f1e1",
      "d7e5"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t7",
    "fen": "1r6/3n2Q1/3k1n2/3b3p/1pp5/2b2B1P/5PP1/3R2K1 w - - 0 28",
    "solution": [
      "f3d5",
      "f6d5",
      "d1d5",
      "d6d5",
      "g7d7",
      "d5e4"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t8",
    "fen": "1r6/3n2Q1/3k4/3n3p/1pp5/2b4P/5PP1/3R2K1 w - - 0 29",
    "solution": [
      "d1d5",
      "d6d5",
      "g7d7",
      "d5e4",
      "d7c7",
      "e4d3"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t9",
    "fen": "1r6/3n2Q1/8/3k3p/1pp5/2b4P/5PP1/6K1 w - - 0 30",
    "solution": [
      "g7d7",
      "d5e4",
      "d7c7",
      "b8h8",
      "c7c4",
      "e4e5"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t10",
    "fen": "6k1/1q1p3p/4p3/p1p1Prbp/2P5/1PN1R1PP/3Q1P2/6K1 w - - 2 31",
    "solution": [
      "f2f4",
      "g5e7",
      "h3h4",
      "f5f8",
      "g1h2",
      "g8h8"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t11",
    "fen": "6k1/1q1p3p/4p3/p1p1P1bp/2P2r2/1PN1R1PP/3Q4/6K1 w - - 0 32",
    "solution": [
      "g3f4",
      "g5f4",
      "c3e2",
      "b7b4",
      "e3g3",
      "f4g3"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t12",
    "fen": "5k2/pp3np1/5p1r/1qpr3p/5pnP/P1b3P1/2Q1R2R/5K2 b - - 1 30",
    "solution": [
      "g4e3",
      "f1g1",
      "e3c2",
      "h2f2",
      "d5d1",
      "g1g2"
    ],
    "theme": "Mate in 12",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t13",
    "fen": "4n2r/1p4b1/2p2kp1/7p/2B3b1/5NN1/2P3PP/2KRR3 w - - 6 33",
    "solution": [
      "g3e4",
      "f6e7",
      "e4d6",
      "e7f6",
      "d6e8",
      "h8e8"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t14",
    "fen": "r2nkr2/1p1b3p/2p2p2/2Q1p1p1/4P1q1/PB3N2/4PK1P/1R1R4 w q - 2 30",
    "solution": [
      "h2h3",
      "g4h3",
      "d1h1",
      "b7b6",
      "c5d6",
      "d8b7"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t15",
    "fen": "3nkr2/1p1b3p/2p2p2/2Q1p1p1/r3P1q1/P4N2/B3PK1P/1R1R4 w - - 4 31",
    "solution": [
      "h2h3",
      "g4e4",
      "d1d7",
      "e8d7",
      "c5f8",
      "a4d4"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t16",
    "fen": "r3rbk1/3p1ppp/b4n2/qP1P2P1/8/2N2B1P/1nQN1P2/R4K1R b - - 0 25",
    "solution": [
      "a5a1",
      "f1g2",
      "a1a3",
      "g5f6",
      "a6b7",
      "d2e4"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t17",
    "fen": "4k3/5p1p/r1n1p3/2P5/P3bpn1/8/2PP1N1P/1R1K3R b - - 0 31",
    "solution": [
      "g4f2",
      "d1c1",
      "e4h1",
      "c1b2",
      "h1d5",
      "b1f1"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "black"
  },
  {
    "id": "t18",
    "fen": "2k5/p2r3p/2p3pb/Qp6/5P2/P1N1r2P/1q4P1/3R1RK1 w - - 0 32",
    "solution": [
      "a5a6",
      "c8d8",
      "a6a7",
      "d7d2",
      "a7e3",
      "d8c7"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t19",
    "fen": "8/p2k3p/2p3pb/Qp6/5P2/P1N1r2P/1q4P1/5RK1 w - - 0 33",
    "solution": [
      "a5a7",
      "d7c8",
      "a7e3",
      "b2a3",
      "f1d1",
      "h6f4"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t20",
    "fen": "r1b1kbnr/ppp3p1/3pp3/3Np2q/4P2p/3P1N2/PPP2P2/R1BQK1R1 w Qkq - 0 14",
    "solution": [
      "d5c7",
      "e8d8",
      "c7a8",
      "g8f6",
      "c1e3",
      "h4h3"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t21",
    "fen": "2Rqr3/1p3kpp/1b3n2/p2np3/1P6/P6P/6B1/4KR2 b - - 0 29",
    "solution": [
      "d8c8",
      "g2d5",
      "f7e7",
      "h3h4",
      "c8c1",
      "e1e2"
    ],
    "theme": "Mate in 11",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t22",
    "fen": "r2q1r1k/1pp1bpp1/p1n4n/3NP2p/4P3/1QP1Bb1P/PP4P1/2KR1B1R w - - 0 14",
    "solution": [
      "g2f3",
      "c6e5",
      "f3f4",
      "e5d7",
      "b3b7",
      "e7c5"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t23",
    "fen": "rr5k/2p1qpp1/p1Q4n/4P2p/b1B1P1P1/2P1B2P/PP6/2K4R b - - 0 18",
    "solution": [
      "a4c6",
      "e5e6",
      "c6e4",
      "h1d1",
      "f7e6",
      "g4h5"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "black"
  },
  {
    "id": "t24",
    "fen": "r4r2/2p3bk/p1b3pp/1p2p3/2B1Pn1N/2P1NPP1/PP6/3RK2R w - - 0 23",
    "solution": [
      "g3f4",
      "b5c4",
      "f4f5",
      "g6g5",
      "h4g6",
      "f8d8"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t25",
    "fen": "r4r2/2p3bk/p1b3pp/4p3/2p1PP1N/2P1NP2/PP6/3RK2R w - - 0 24",
    "solution": [
      "f4f5",
      "g6g5",
      "h4g6",
      "f8d8",
      "e3c4",
      "d8d1"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t26",
    "fen": "r4r2/2p3bk/p1b4p/4pp2/2p1P2N/2P1NP2/PP6/3RK2R w - - 0 25",
    "solution": [
      "h4f5",
      "f8f6",
      "d1d2",
      "a8f8",
      "d2g2",
      "f8f7"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t27",
    "fen": "3R4/2p3k1/p1b4p/4p3/2p1P3/2P1NP2/Pr6/4K2R w - - 0 29",
    "solution": [
      "e3f5",
      "g7f7",
      "h1h6",
      "b2b6",
      "d8c8",
      "c6d7"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t28",
    "fen": "r3kb1r/ppp1q1p1/3p4/3P1P2/3p1p2/3B4/PP5P/2RK3b b kq - 0 21",
    "solution": [
      "h8h2",
      "c1c2",
      "h1f3",
      "c2e2",
      "f3e2",
      "d1c2"
    ],
    "theme": "Mate in 8",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t29",
    "fen": "r3kb1r/ppp1q1p1/3p4/3P1P2/3p1p2/3B1b2/PPK4P/2R5 b kq - 2 22",
    "solution": [
      "h8h2",
      "c2b1",
      "f3e4",
      "d3e4",
      "e7e4",
      "b1a1"
    ],
    "theme": "Mate in 9",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t30",
    "fen": "1k1r1br1/1bq1n3/pp2p1Bp/2p2p2/2PpPPpP/2BPN3/PP2N1P1/3RQRK1 w - - 0 21",
    "solution": [
      "g6f7",
      "e7d5",
      "e2d4",
      "c5d4",
      "c4d5",
      "c7f7"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t31",
    "fen": "1r1qk2r/p3p2p/3P1bP1/n1p2b2/2P5/Pp2PN1P/1B3P2/1Q1RKBR1 w - - 0 22",
    "solution": [
      "b1f5",
      "d8d7",
      "f5h5",
      "h7g6",
      "h5g6",
      "e8d8"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t32",
    "fen": "3qk2r/pr2p2p/3P1bP1/n1p2Q2/2P5/Pp2PN1P/1B3P2/3RKBR1 w - - 1 23",
    "solution": [
      "g6h7",
      "e8f8",
      "d6e7",
      "d8e7",
      "b2f6",
      "h8h7"
    ],
    "theme": "Mate in 8",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t33",
    "fen": "2kr4/1b4p1/p2qp3/1pb2P1r/4p1N1/4P2P/PPP1Q3/2KR2R1 w - - 0 28",
    "solution": [
      "d1d6",
      "d8d6",
      "f5e6",
      "d6e6",
      "e2f2",
      "e6e7"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t34",
    "fen": "r2q2k1/pppb2rp/3p2pB/3npPN1/3n2P1/2PP4/PP2BP1P/R2Q1R1K w - - 1 16",
    "solution": [
      "c3d4",
      "g6f5",
      "g4f5",
      "d8g5",
      "h6g5",
      "g7g5"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t35",
    "fen": "1rb2r1k/1p1p2pp/p2b3n/2pN1p2/P1PnP2q/R1NP3P/1P2BPP1/2BQK2R w K - 3 16",
    "solution": [
      "e4f5",
      "h6f5",
      "c3e4",
      "h7h6",
      "e4d6",
      "f5d6"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t36",
    "fen": "6k1/8/p1p1pp1p/1p1pPB1q/1P1P2p1/P1P2rP1/3Q1PK1/5R2 b - - 0 32",
    "solution": [
      "h5h3",
      "g2g1",
      "f3f5",
      "d2d3",
      "f6e5",
      "f1e1"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t37",
    "fen": "r6r/2pk2p1/P1b2p2/2q1n1B1/Pp1pP1P1/3P2Qp/2P2N1P/R2K1R1B b - - 0 31",
    "solution": [
      "f6g5",
      "f2h3",
      "a8a6",
      "h3g5",
      "c6a4",
      "d1e1"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t38",
    "fen": "rn1qkb1r/1ppbpppp/5n2/p2P4/Q2P4/6P1/PP2PPBP/RNB2RK1 b kq - 0 8",
    "solution": [
      "d7a4",
      "b1c3",
      "a4d7",
      "e2e4",
      "e7e6",
      "d5e6"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "black"
  },
  {
    "id": "t39",
    "fen": "rn1qkb1r/1ppb1ppp/4p3/p2B4/3P4/1Q4P1/PP2PP1P/RNB2RK1 b kq - 0 10",
    "solution": [
      "e6d5",
      "b3d5",
      "d7c6",
      "d5e5",
      "d8e7",
      "e5f4"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t40",
    "fen": "4rk1r/2n1qp2/8/3p2p1/3P3p/2Q3P1/PP1bPP1P/R5K1 b - - 3 27",
    "solution": [
      "d2c3",
      "e2e4",
      "c3d4",
      "e4e5",
      "h4g3",
      "h2g3"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "black"
  },
  {
    "id": "t41",
    "fen": "4k3/1b1n1p2/1R1pN2p/Q2P4/P2qPN2/r7/1PP3P1/1KBR4 w - - 1 28",
    "solution": [
      "b6b7",
      "f7e6",
      "d1d4",
      "a3a1",
      "b1a1",
      "e8e7"
    ],
    "theme": "Mate in 7",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t42",
    "fen": "4k3/1R1n1p2/1q1pN2p/Q2P4/P3PN2/r7/1PP3P1/1KBR4 w - - 1 29",
    "solution": [
      "a5a8",
      "e8e7",
      "f4g6",
      "e7f6",
      "a8h8",
      "f6g6"
    ],
    "theme": "Mate in 4",
    "difficulty": "medium",
    "turn": "white"
  },
  {
    "id": "t43",
    "fen": "3qk2r/3nbppp/p3p3/1p6/3nQBP1/P1p4P/5P2/RN2K1NR b KQk - 1 16",
    "solution": [
      "d7c5",
      "f4c7",
      "c5e4",
      "c7d8",
      "e8d8",
      "b1c3"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t44",
    "fen": "7r/4kppp/p3pb2/1p6/4N1P1/P4n1P/5P2/RN3K1R b - - 0 22",
    "solution": [
      "f6a1",
      "f1g2",
      "f3h4",
      "g2g3",
      "h4g6",
      "f2f4"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t45",
    "fen": "2r4k/p2p1p1n/1p2r3/1b6/Pn1p3P/6P1/1P1B1PBR/R5K1 b - - 1 26",
    "solution": [
      "b4c2",
      "a1c1",
      "b5a4",
      "g2d5",
      "e6e7",
      "f2f3"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t46",
    "fen": "4r3/1ppq1pk1/5nn1/pN2b2Q/1Pr5/8/P2P1N1R/R5K1 b - - 1 28",
    "solution": [
      "f6h5",
      "h2h5",
      "c4g4",
      "g1f1",
      "d7b5",
      "d2d3"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "black"
  },
  {
    "id": "t47",
    "fen": "r2qkb1r/pb1p1pp1/4p3/1Nn4p/4NP2/P3P3/1PP3PP/R1BQKB1R b KQkq - 0 10",
    "solution": [
      "c5e4",
      "d1f3",
      "a8b8",
      "f1d3",
      "d8h4",
      "g2g3"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t48",
    "fen": "r2qkb1r/pb1p1pp1/4p3/8/3QnP1p/P1N1P3/1PP3PP/R1B1KB1R b KQkq - 1 12",
    "solution": [
      "e4c3"
    ],
    "theme": "Winning tactic",
    "difficulty": "hard",
    "turn": "black"
  },
  {
    "id": "t49",
    "fen": "r1b2rk1/pPp3bp/3p4/3Pp3/2B2B2/2PP1R2/1P3P2/R3K3 b - - 0 27",
    "solution": [
      "c8b7",
      "d3d4",
      "f8f4",
      "f3f4",
      "e5f4",
      "b2b4"
    ],
    "theme": "Winning tactic",
    "difficulty": "medium",
    "turn": "black"
  },
  {
    "id": "t50",
    "fen": "r1b5/pp2p3/qk2P3/3p4/1p1Nn1n1/2P1QR1P/PB1N2P1/R5K1 w - - 2 25",
    "solution": [
      "h3g4",
      "e4d2",
      "e3d2",
      "a6a4",
      "c3b4",
      "a7a5"
    ],
    "theme": "Winning tactic",
    "difficulty": "easy",
    "turn": "white"
  },
  {
    "id": "t51",
    "fen": "r1b5/pp2p3/1k2P3/3p4/qP1N2P1/4QR2/PB1n2P1/R5K1 w - - 0 27",
    "solution": [
      "d4b5",
      "d5d4",
      "e3d4",
      "b6b5",
      "d4c5",
      "b5a6"
    ],
    "theme": "Mate in 7",
    "difficulty": "hard",
    "turn": "white"
  },
  {
    "id": "t52",
    "fen": "r1b5/pp2p3/4P3/1k1p4/qP4P1/1N2QR2/PB1n2P1/R5K1 w - - 2 28",
    "solution": [
      "e3d2",
      "b7b6",
      "d2d3",
      "b5c6",
      "b4b5",
      "a4b5"
    ],
    "theme": "Mate in 9",
    "difficulty": "hard",
    "turn": "white"
  }
];
