// AUTO-GENERATED by scripts/gen-tactics.mjs — verified by Stockfish.
// Each position has a single winning move (the first entry of `solution`).
export interface Puzzle {
  id: string;
  fen: string;
  /** UCI moves; solution[0] is the key move, the rest is the main line. */
  solution: string[];
  theme: string;
  turn: 'white' | 'black';
}

export const PUZZLES: Puzzle[] = [
  {
    "id": "t1",
    "fen": "8/R4p2/1kpbb2p/4B3/4Pp2/1P1K1P2/2P4P/5Br1 w - - 7 31",
    "solution": [
      "e5d4",
      "c6c5",
      "d4g1",
      "b6a7",
      "e4e5",
      "e6f5"
    ],
    "theme": "Winning tactic",
    "turn": "white"
  },
  {
    "id": "t2",
    "fen": "1rbk4/R3n3/1p1Np2b/6P1/1pP1p3/4BN1p/1P3K1P/4R3 w - - 2 28",
    "solution": [
      "f3e5",
      "b8b7",
      "a7b7",
      "c8b7",
      "e3b6"
    ],
    "theme": "Mate in 3",
    "turn": "white"
  },
  {
    "id": "t3",
    "fen": "rq5r/1p2kp2/2bppn1p/pB1p2p1/Pn1P4/1QP1P3/1P1NNPPP/R3K2R w KQ - 1 17",
    "solution": [
      "c3b4",
      "c6b5",
      "a4b5",
      "a5b4",
      "a1c1",
      "h8c8"
    ],
    "theme": "Winning tactic",
    "turn": "white"
  },
  {
    "id": "t4",
    "fen": "1kn3rr/1ppq4/p2b4/4p3/8/P2P1RNP/1PP2QnK/1R2B3 b - - 1 32",
    "solution": [
      "d7h3",
      "h2g1",
      "g2f4",
      "f2a7",
      "c8a7",
      "f3f4"
    ],
    "theme": "Mate in 9",
    "turn": "black"
  },
  {
    "id": "t5",
    "fen": "3n3k/1pQb1np1/3p4/3p1p1p/rP3P2/2B1q3/1P4PP/R1R2K2 b - - 1 30",
    "solution": [
      "d7b5",
      "c7c4",
      "b5c4"
    ],
    "theme": "Mate in 2",
    "turn": "black"
  },
  {
    "id": "t6",
    "fen": "3n3k/1p3np1/3p4/1b1p1p1p/rPQ2P2/2B1q3/1P4PP/R1R2K2 b - - 3 31",
    "solution": [
      "b5c4"
    ],
    "theme": "Mate in 1",
    "turn": "black"
  },
  {
    "id": "t7",
    "fen": "r1B3k1/1pq1brp1/5n1p/2p1n3/3P4/1Q2P3/3BNPPP/1R2K2R b K - 0 20",
    "solution": [
      "c5c4",
      "b3b7",
      "e5d3",
      "e1d1",
      "d3f2",
      "d1c2"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t8",
    "fen": "r1B3k1/1Qq1brp1/5n1p/4n3/2pP4/4P3/3BNPPP/1R2K2R b K - 0 21",
    "solution": [
      "e5d3",
      "e1f1",
      "c7c8",
      "b7c8",
      "a8c8",
      "e2g3"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t9",
    "fen": "4r1k1/5rp1/7p/1R4bn/2pP1n2/2N1PP2/3B1KPP/7R b - - 5 29",
    "solution": [
      "f4d3",
      "f2e2",
      "g5e3",
      "d2e3",
      "h5f4",
      "e2d2"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t10",
    "fen": "r1bqkb1r/p1pp1ppp/2n1p2n/1p4P1/5P2/4P3/PPPPK2P/RNBQ1BNR b kq - 0 5",
    "solution": [
      "h6f5",
      "e3e4",
      "c8b7",
      "c2c3",
      "c6e7",
      "d2d3"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t11",
    "fen": "q3k3/1bp4r/3bpB1p/1p1p2P1/7P/1PN1PNn1/r1nP2B1/3K2QR b - - 3 23",
    "solution": [
      "c2b4",
      "c3a4",
      "d5d4",
      "d1c1",
      "g3e2",
      "c1d1"
    ],
    "theme": "Mate in 15",
    "turn": "black"
  },
  {
    "id": "t12",
    "fen": "4k3/1bp4r/3bpB1p/1p1p2P1/7P/qPN1PNn1/r1nP4/3K1BQR b - - 5 24",
    "solution": [
      "a2a1",
      "d1c2",
      "a1c1",
      "c2d3",
      "a3b3",
      "e3e4"
    ],
    "theme": "Mate in 8",
    "turn": "black"
  },
  {
    "id": "t13",
    "fen": "4k3/1bp4r/3bpB1p/1p1p2P1/3n3P/1q2PNn1/N2P4/4KBQR b - - 2 26",
    "solution": [
      "d4f3",
      "e1f2",
      "f3g1",
      "h1g1",
      "g3e4",
      "f2g2"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t14",
    "fen": "4k3/1bp4r/2nbpB1p/3p2P1/4n2P/1qpBPN2/3P4/4K1QR b - - 1 30",
    "solution": [
      "c3d2",
      "e1e2",
      "b3d3",
      "e2d3",
      "d2d1q",
      "g1d1"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t15",
    "fen": "4k3/1bp4r/2nbpB1p/3p2P1/4n2P/1q1BP3/3N4/4K1QR b - - 0 31",
    "solution": [
      "b3d3",
      "d2e4",
      "d5e4",
      "g1g2",
      "d3e3",
      "e1d1"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t16",
    "fen": "4k3/1bp4r/2nbpB1p/3p2P1/4N2P/3qP3/8/4K1QR b - - 0 32",
    "solution": [
      "d5e4",
      "g1g2",
      "d3e3",
      "e1d1",
      "e3b3",
      "g2c2"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t17",
    "fen": "r1b1kb1r/1p3qpp/p7/2ppnp2/P2N2n1/1PP1P3/R2NBPPP/2BQ1RK1 b kq - 1 12",
    "solution": [
      "c5d4",
      "e3d4",
      "e5g6",
      "f1e1",
      "f8e7",
      "d2c4"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  },
  {
    "id": "t18",
    "fen": "r2qkb1r/p1p2ppp/p4n2/3pp3/6b1/1P2PN2/PBPP1PPP/RN1QK2R b KQkq - 1 7",
    "solution": [
      "e5e4",
      "h2h3",
      "g4h5",
      "g2g4",
      "f6g4",
      "f3d4"
    ],
    "theme": "Winning tactic",
    "turn": "black"
  }
];
