import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);

// Register the Workbox service worker generated by vite-plugin-pwa (autoUpdate:
// a new deploy activates on the next visit and reloads onto the new version).
// No-op in dev, where the plugin is disabled so it can't interfere with HMR.
registerSW({
  immediate: true,
  // Long-lived windows (installed PWAs left open) otherwise rely on the
  // browser's >24h update heuristics; poll hourly so deploys land sooner.
  onRegisteredSW(_swUrl, registration) {
    if (registration) setInterval(() => void registration.update(), 60 * 60 * 1000);
  },
});
