/**
 * Track 1 — Chess basics: a hands-on rules course for total beginners.
 * Every exercise is FEN + goal data interpreted by learn/engine.ts and
 * machine-validated in learn/content.test.ts (legal FENs, solvable goals,
 * playable scripted lines).
 */
import type { Lesson } from '../types';

export const BASICS_LESSONS: Lesson[] = [
  {
    id: 'rules-pawn',
    title: 'The Pawn',
    icon: '♙',
    summary: 'Small steps, big dreams — learn how pawns march and capture.',
    steps: [
      {
        kind: 'info',
        title: 'Meet the pawn',
        text: 'Pawns are your little soldiers. They only march forward — never backward — one square at a time. On their very first move they may sprint two squares.',
        fen: '7k/8/8/8/8/8/4P3/7K w - - 0 1',
        shapes: [
          { orig: 'e2', dest: 'e3', brush: 'green' },
          { orig: 'e2', dest: 'e4', brush: 'blue' },
        ],
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/4P3/7K w - - 0 1',
        prompt: 'Your pawn has never moved, so it can sprint. Move it two squares forward, to the circled square.',
        goal: { type: 'move', moves: ['e2e4'] },
        shapes: [{ orig: 'e4', brush: 'green' }],
        hint: 'One square is allowed too, but here we want the double step: e2 to e4.',
        success: 'The famous first move e4 — you just played it!',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/4P3/8/8/7K w - - 0 1',
        prompt: 'After its first move a pawn walks one square at a time. March it one more step.',
        goal: { type: 'move', moves: ['e4e5'] },
        shapes: [{ orig: 'e5', brush: 'green' }],
        success: 'Step by step — that pawn is going places.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/3p4/4P3/8/8/7K w - - 0 1',
        prompt: 'Pawns capture differently than they move: one square diagonally forward. Capture the enemy pawn!',
        goal: { type: 'capture' },
        hint: 'Straight ahead is blocked territory for captures — take diagonally, onto d5.',
        success: 'Gotcha! Pawns strike sideways.',
      },
    ],
  },
  {
    id: 'rules-knight',
    title: 'The Knight',
    icon: '♘',
    summary: 'The trickster of the board — it jumps in an L and leaps over anything.',
    steps: [
      {
        kind: 'info',
        title: 'Meet the knight',
        text: 'The knight moves in an “L”: two squares in one direction, then one square sideways. It is the only piece that can jump over other pieces — friend or foe.',
        fen: '7k/8/8/8/8/8/8/1N5K w - - 0 1',
        shapes: [
          { orig: 'b1', dest: 'a3', brush: 'blue' },
          { orig: 'b1', dest: 'c3', brush: 'blue' },
          { orig: 'b1', dest: 'd2', brush: 'blue' },
        ],
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/8/1N5K w - - 0 1',
        prompt: 'Hop the knight to the circled square — two up, one over.',
        goal: { type: 'move', moves: ['b1c3'] },
        shapes: [{ orig: 'c3', brush: 'green' }],
        success: 'Clip-clop! That is the L-shape.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/3N4/8/8/7K w - - 0 1',
        prompt: 'From the middle of the board a knight reaches eight squares. Jump to the circled one.',
        goal: { type: 'move', moves: ['d4e6'] },
        shapes: [{ orig: 'e6', brush: 'green' }],
        success: 'A knight in the center is a happy knight.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/5p2/4PPPP/4K1N1 w - - 0 1',
        prompt: 'The knight is boxed in — but knights jump! Leap over your own pawns and capture the enemy pawn with the knight.',
        goal: { type: 'capture' },
        onlyFrom: ['g1'],
        hint: 'The knight on g1 can jump straight over the wall and land on f3.',
        success: 'Over the wall and straight onto the target. No piece can block a knight!',
      },
    ],
  },
  {
    id: 'rules-bishop',
    title: 'The Bishop',
    icon: '♗',
    summary: 'A laser on diagonals — but forever stuck on one color.',
    steps: [
      {
        kind: 'info',
        title: 'Meet the bishop',
        text: 'The bishop slides any number of squares along a diagonal. Each bishop spends its whole life on one color — a light-squared bishop can never touch a dark square.',
        fen: '7k/8/8/8/8/8/8/2B4K w - - 0 1',
        shapes: [
          { orig: 'c1', dest: 'h6', brush: 'blue' },
          { orig: 'c1', dest: 'a3', brush: 'blue' },
        ],
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/8/2B4K w - - 0 1',
        prompt: 'Slide the bishop along the diagonal to the circled square.',
        goal: { type: 'move', moves: ['c1g5'] },
        shapes: [{ orig: 'g5', brush: 'green' }],
        success: 'Smooth. Diagonals only, as far as you like.',
      },
      {
        kind: 'exercise',
        fen: '7k/6b1/8/8/8/8/8/B6K w - - 0 1',
        prompt: 'Your bishop sees all the way across the board. Capture the enemy bishop!',
        goal: { type: 'capture' },
        hint: 'Follow the long diagonal from a1 — it runs all the way to g7.',
        success: 'Sniped from the other corner of the board.',
      },
    ],
  },
  {
    id: 'rules-rook',
    title: 'The Rook',
    icon: '♖',
    summary: 'A heavy tower that owns ranks and files.',
    steps: [
      {
        kind: 'info',
        title: 'Meet the rook',
        text: 'The rook moves any number of squares in a straight line — up, down, left or right. Rooks love open files where nothing blocks their path.',
        fen: '7k/8/8/8/8/8/8/R6K w - - 0 1',
        shapes: [
          { orig: 'a1', dest: 'a7', brush: 'blue' },
          { orig: 'a1', dest: 'g1', brush: 'blue' },
        ],
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/8/R6K w - - 0 1',
        prompt: 'Zoom the rook straight up the open file to the circled square.',
        goal: { type: 'move', moves: ['a1a5'] },
        shapes: [{ orig: 'a5', brush: 'green' }],
        success: 'Full speed ahead on the open file.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/2p5/8/8/8/2R4K w - - 0 1',
        prompt: 'The enemy pawn stands in your rook’s lane. Capture it!',
        goal: { type: 'capture' },
        hint: 'The rook and the pawn share the c-file — charge straight up it.',
        success: 'Steamrolled.',
      },
    ],
  },
  {
    id: 'rules-queen',
    title: 'The Queen',
    icon: '♕',
    summary: 'Rook + bishop in one — the strongest piece on the board.',
    steps: [
      {
        kind: 'info',
        title: 'Meet the queen',
        text: 'The queen combines the rook and the bishop: any number of squares in a straight line or along a diagonal. She is your most powerful piece — and everyone knows it, so keep her safe.',
        fen: '7k/8/8/8/8/8/8/3Q3K w - - 0 1',
        shapes: [
          { orig: 'd1', dest: 'd7', brush: 'blue' },
          { orig: 'd1', dest: 'h5', brush: 'blue' },
          { orig: 'd1', dest: 'a4', brush: 'blue' },
        ],
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/8/3Q3K w - - 0 1',
        prompt: 'Glide the queen along the diagonal to the circled square.',
        goal: { type: 'move', moves: ['d1h5'] },
        shapes: [{ orig: 'h5', brush: 'green' }],
        success: 'Queen on the loose!',
      },
      {
        kind: 'exercise',
        fen: '7k/8/3n4/8/8/8/8/3Q3K w - - 0 1',
        prompt: 'Now use her rook powers: capture the knight straight up the file.',
        goal: { type: 'capture' },
        success: 'Straight lines, diagonals — the queen does it all.',
      },
    ],
  },
  {
    id: 'rules-king',
    title: 'The King',
    icon: '♔',
    summary: 'Slow but precious — one step at a time, never into danger.',
    steps: [
      {
        kind: 'info',
        title: 'Meet the king',
        text: 'The king moves one square in any direction. He is not strong, but he is everything: if your king is trapped, you lose the game. He may never step onto a square an enemy piece attacks.',
        fen: '7k/8/8/8/8/8/8/4K3 w - - 0 1',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/8/4K3 w - - 0 1',
        prompt: 'Take one royal step to the circled square.',
        goal: { type: 'move', moves: ['e1e2'] },
        shapes: [{ orig: 'e2', brush: 'green' }],
        success: 'Slow and steady.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/4p3/3PK3/8 w - - 0 1',
        prompt: 'The king can capture too. That enemy pawn wandered too close and nobody defends it — take it with your king!',
        goal: { type: 'capture' },
        onlyFrom: ['e2'],
        success: 'Handled personally, by royal decree.',
      },
      {
        kind: 'exercise',
        fen: '3r3k/8/8/8/8/8/8/4K3 w - - 0 1',
        prompt: 'The enemy rook guards the whole d-file, so your king cannot step there — pick up the king and see for yourself. Then walk him to the circled square.',
        goal: { type: 'move', moves: ['e1f2'] },
        shapes: [{ orig: 'f2', brush: 'green' }, { orig: 'd8', dest: 'd1', brush: 'red' }],
        hint: 'Squares on the d-file are off-limits — the rook attacks them all. Head to f2.',
        success: 'Exactly — kings must always respect enemy firepower.',
      },
    ],
  },
  {
    id: 'rules-capturing',
    title: 'Capturing Safely',
    icon: '⚔️',
    summary: 'Free snacks vs. poisoned bait — check who defends before you grab.',
    steps: [
      {
        kind: 'info',
        title: 'Look before you take',
        text: 'You capture by moving onto an enemy piece’s square — it leaves the board for good. But beware: if that piece is defended, its friend will capture you right back. Always ask: is it free, or is it bait?',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/2n3p1/5p2/4B3/8/7K w - - 0 1',
        prompt: 'Your bishop can capture two different pieces. One is free, one is protected. Make the safe capture!',
        goal: { type: 'move', moves: ['e3c5'] },
        hint: 'The pawn on f4 is guarded by the pawn on g5 — you would lose your bishop. The knight on c5 has no friends nearby.',
        success: 'A whole knight, free of charge. That is how you shop.',
      },
    ],
  },
  {
    id: 'rules-check',
    title: 'Check!',
    icon: '⚠️',
    summary: 'When your king is attacked you must act — run, block, or fight back.',
    steps: [
      {
        kind: 'info',
        title: 'What is check?',
        text: 'When an enemy piece attacks your king, that is check — and you must deal with it immediately. You have three options: move the king, block the attack, or capture the attacker.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/8/8/8/r3K3 w - - 0 1',
        prompt: 'The rook has your king in check along the first rank. Move your king somewhere safe — the board only lets you pick safe squares.',
        goal: { type: 'any' },
        success: 'Crisis averted. Notice you could not stay on the first rank.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/8/1b6/8/2N5/4K3 w - - 0 1',
        prompt: 'Check again — but this attacker is unprotected. Instead of running, capture the bishop!',
        goal: { type: 'capture' },
        hint: 'Your knight on c2 can jump right onto the bishop. Best way out of check: remove the problem.',
        success: 'Counter-attack! The best defense.',
      },
    ],
  },
  {
    id: 'rules-checkmate',
    title: 'Checkmate & Stalemate',
    icon: '🏁',
    summary: 'How games are won — and the sneaky draw that ruins parties.',
    steps: [
      {
        kind: 'info',
        title: 'Checkmate ends the game',
        text: 'Checkmate is a check the enemy king cannot escape: no safe square, no block, no capture. The game ends instantly — that is how you win. Time to deliver one!',
      },
      {
        kind: 'exercise',
        fen: '6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',
        prompt: 'The black king hides behind his pawns — but the back door is wide open. Deliver checkmate in one move!',
        goal: { type: 'checkmate' },
        hint: 'Send the rook to the last rank. The king’s own pawns block every escape.',
        success: 'The classic back-rank mate. Game over!',
      },
      {
        kind: 'exercise',
        fen: '6k1/8/6K1/8/8/8/8/Q7 w - - 0 1',
        prompt: 'Your king already stands guard. Find the queen move that ends everything.',
        goal: { type: 'checkmate' },
        hint: 'Your king covers the escape squares on the 7th rank — check the king along the 8th rank, or land the queen right next to him, protected.',
        success: 'Checkmate! King and queen — the classic duo.',
      },
      {
        kind: 'info',
        title: 'Stalemate: the trap draw',
        text: 'If a player is NOT in check but has NO legal move, that is stalemate — a draw, no matter how far ahead you are! Here Black, to move, has nowhere to go but is not in check. Half a point each. When you are winning big, always leave the enemy king one square to shuffle on until you are ready to mate.',
        fen: '7k/8/6Q1/8/8/8/8/6K1 b - - 0 1',
        shapes: [
          { orig: 'g7', brush: 'red' },
          { orig: 'g8', brush: 'red' },
          { orig: 'h7', brush: 'red' },
        ],
      },
    ],
  },
  {
    id: 'rules-castling',
    title: 'Castling',
    icon: '🏰',
    summary: 'The two-for-one special: tuck your king away and activate a rook.',
    steps: [
      {
        kind: 'info',
        title: 'The only double move',
        text: 'Castling is the one move where two of your pieces move at once: the king slides two squares toward a rook, and that rook hops to the other side of the king. Conditions: neither piece has moved yet, the squares between are empty, and the king may not castle out of, through, or into check.',
      },
      {
        kind: 'exercise',
        fen: '4k3/8/8/8/8/8/8/4K2R w K - 0 1',
        prompt: 'Castle kingside: slide your king two squares toward the rook.',
        goal: { type: 'move', moves: ['e1g1'] },
        shapes: [{ orig: 'g1', brush: 'green' }],
        hint: 'Move the king from e1 to g1 — the rook will jump around him automatically.',
        success: 'Castled! King safe, rook in the game. Two chores, one move.',
      },
      {
        kind: 'exercise',
        fen: '4k3/8/8/8/8/8/8/R3K3 w Q - 0 1',
        prompt: 'Now the long version: castle queenside, toward the far rook.',
        goal: { type: 'move', moves: ['e1c1'] },
        shapes: [{ orig: 'c1', brush: 'green' }],
        hint: 'King from e1 to c1 — two squares toward the a1 rook.',
        success: 'Long castle! Same idea, bigger rook hop.',
      },
    ],
  },
  {
    id: 'rules-enpassant',
    title: 'En Passant',
    icon: '🥖',
    summary: 'The rule everyone swears is made up. It isn’t.',
    steps: [
      {
        kind: 'info',
        title: '“In passing”',
        text: 'When an enemy pawn uses its two-square sprint and lands directly beside your pawn, you may capture it as if it had only moved one square. One catch: you must do it immediately — next move, the chance is gone forever.',
      },
      {
        kind: 'exercise',
        fen: '7k/8/8/4Pp2/8/8/8/7K w - f6 0 1',
        prompt: 'The black pawn just sprinted from f7 to f5, right past yours. Capture it en passant — land on the circled square!',
        goal: { type: 'move', moves: ['e5f6'] },
        shapes: [{ orig: 'f6', brush: 'green' }],
        hint: 'Move your e5 pawn diagonally to f6 — the f5 pawn vanishes as if you caught it mid-sprint.',
        success: 'En passant! Now you can settle internet arguments about it.',
      },
    ],
  },
  {
    id: 'rules-promotion',
    title: 'Promotion',
    icon: '👑',
    summary: 'Walk a pawn to the end of the board and crown it.',
    steps: [
      {
        kind: 'info',
        title: 'The pawn’s dream',
        text: 'A pawn that reaches the far end of the board is promoted: it transforms into a queen, rook, bishop or knight — your choice, and almost always a queen. Yes, you can have two queens. Or more.',
      },
      {
        kind: 'exercise',
        fen: '7k/4P3/8/8/8/8/8/7K w - - 0 1',
        prompt: 'One step from glory. March your pawn to the last rank and crown a new queen!',
        goal: { type: 'promotion', piece: 'q' },
        shapes: [{ orig: 'e8', brush: 'green' }],
        success: 'Long live the (second) queen! This wins endless endgames.',
      },
    ],
  },
];
