// Lazy CSS loaders for the alternate piece sets.
//
// The default set (cburnett) is imported statically in index.css so the board
// paints instantly. Every other set lives in its own committed CSS file
// (generated by scripts/gen-piece-sets.mjs) and is fetched on demand the first
// time it's needed — keeping the initial bundle small.
// import.meta.glob is compiled away by Vite; under plain node (unit tests
// import the stores, which transitively reach this module) it doesn't exist,
// so calling it throws and we fall back to no lazy loaders.
let loaders: Record<string, () => Promise<unknown>> = {};
try {
  loaders = import.meta.glob('./pieces/*.css');
} catch {
  // Not running under Vite (e.g. node-based unit tests) — no lazy CSS to load.
}

// Keyed by glob path. cburnett is already loaded eagerly via index.css.
const requested = new Set<string>(['./pieces/cburnett.css']);

function load(key: string): void {
  if (requested.has(key)) return;
  const loader = loaders[key];
  if (!loader) return;
  requested.add(key);
  void loader();
}

/** Ensure the CSS for a piece set is loaded (no-op if already requested). */
export function loadPieceSet(id: string): void {
  load(`./pieces/${id}.css`);
}

/** Load every set's CSS — used to render the previews in Settings. */
export function loadAllPieceSets(): void {
  for (const key in loaders) load(key);
}
