// Lazy CSS loaders for the alternate piece sets.
//
// The default set (cburnett) is imported statically in index.css so the board
// paints instantly. Every other set lives in its own committed CSS file
// (generated by scripts/gen-piece-sets.mjs) and is fetched on demand the first
// time it's needed — keeping the initial bundle small.
const loaders = import.meta.glob('./pieces/*.css');

// Keyed by glob path. cburnett is already loaded eagerly via index.css.
const requested = new Set<string>(['./pieces/cburnett.css']);

function load(key: string): void {
  if (requested.has(key)) return;
  const loader = loaders[key];
  if (!loader) return;
  requested.add(key);
  void loader();
}

/** Ensure the CSS for a piece set is loaded (no-op if already requested). */
export function loadPieceSet(id: string): void {
  load(`./pieces/${id}.css`);
}

/** Load every set's CSS — used to render the previews in Settings. */
export function loadAllPieceSets(): void {
  for (const key in loaders) load(key);
}
