// Generate verified tactics puzzles.
//
// Strategy: let a weak Stockfish play itself (with randomised openings) to
// produce natural blunders, then analyse every resulting position with a strong
// Stockfish. A position is a puzzle when exactly one move is winning for the
// side to move (best is decisive, second-best is not) — i.e. a real "find the
// only move" tactic. The engine's best move is the verified solution.
//
// Usage:  node scripts/gen-tactics.mjs [count]
import { spawn } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SF = path.join(ROOT, 'engines/bin/stockfish');
// chess.js lives in the workspace packages, not next to this script.
const require = createRequire(path.join(ROOT, 'apps/server/package.json'));
const { Chess } = require('chess.js');
const TARGET = Number(process.argv[2] ?? 24);

function makeEngine(bin, args = []) {
  const p = spawn(bin, args);
  let buf = '';
  let current = null;
  p.stdout.on('data', (d) => {
    buf += d;
    let i;
    while ((i = buf.indexOf('\n')) >= 0) {
      const line = buf.slice(0, i).trim();
      buf = buf.slice(i + 1);
      if (current) current(line);
    }
  });
  const send = (c) => p.stdin.write(c + '\n');
  const wait = (pred) =>
    new Promise((res) => {
      const prev = current;
      current = (line) => {
        prev?.(line);
        if (pred(line)) {
          current = prev;
          res(line);
        }
      };
    });
  return {
    send,
    set: (fn) => (current = fn),
    wait,
    async init() {
      send('uci');
      await wait((l) => l === 'uciok');
      send('isready');
      await wait((l) => l === 'readyok');
    },
    kill: () => p.kill('SIGKILL'),
  };
}

function parseInfo(line) {
  const mpv = Number(/multipv (\d+)/.exec(line)?.[1] ?? 1);
  const cp = /score cp (-?\d+)/.exec(line);
  const mate = /score mate (-?\d+)/.exec(line);
  const pv = /\bpv (.+)$/.exec(line)?.[1].split(' ') ?? [];
  return { mpv, cp: cp ? Number(cp[1]) : undefined, mate: mate ? Number(mate[1]) : undefined, pv };
}

// Run a search, return latest line per multipv (scores are side-to-move POV).
function search(eng, fen, { movetime, multipv = 1, skill }) {
  return new Promise((res) => {
    const lines = new Map();
    eng.set((line) => {
      if (line.startsWith('info ') && line.includes(' pv ')) {
        const info = parseInfo(line);
        lines.set(info.mpv, info);
      } else if (line.startsWith('bestmove')) {
        res({ best: line.split(/\s+/)[1], lines });
      }
    });
    eng.send(`setoption name MultiPV value ${multipv}`);
    if (skill !== undefined) {
      eng.send('setoption name UCI_LimitStrength value false');
      eng.send(`setoption name Skill Level value ${skill}`);
    } else {
      eng.send('setoption name Skill Level value 20');
    }
    eng.send(`position fen ${fen}`);
    eng.send(`go movetime ${movetime}`);
  });
}

const cpOf = (info, cap = 100000) => {
  if (info.mate !== undefined) return info.mate > 0 ? cap - info.mate * 100 : -cap - info.mate * 100;
  return info.cp ?? 0;
};
const decisive = (info, capAbs = 2500) => {
  if (info.mate !== undefined) return info.mate > 0; // mating for stm
  return info.cp !== undefined && info.cp >= 200 && info.cp <= capAbs;
};
// A genuine "only move" tactic: best is decisive AND clearly unique.
const isTactic = (m1, m2) => {
  if (!m1 || !decisive(m1) || !m1.pv[0]) return false;
  if (!m2) return true;
  const notWinning2 = m2.mate !== undefined ? m2.mate < 0 : (m2.cp ?? 0) <= 80;
  return notWinning2 || cpOf(m1) - cpOf(m2) >= 250;
};

function classify(info) {
  if (info.mate !== undefined && info.mate > 0) return info.mate <= 1 ? 'Mate in 1' : `Mate in ${info.mate}`;
  return 'Winning tactic';
}

function writeOut(puzzles) {
  const out =
    `// AUTO-GENERATED by scripts/gen-tactics.mjs — verified by Stockfish.\n` +
    `// Each position has a single winning move (the first entry of \`solution\`).\n` +
    `export interface Puzzle {\n` +
    `  id: string;\n  fen: string;\n  /** UCI moves; solution[0] is the key move, the rest is the main line. */\n` +
    `  solution: string[];\n  theme: string;\n  turn: 'white' | 'black';\n}\n\n` +
    `export const PUZZLES: Puzzle[] = ${JSON.stringify(puzzles, null, 2)};\n`;
  writeFileSync(path.join(ROOT, 'apps/web/src/trainers/tactics.ts'), out);
}

async function main() {
  const player = makeEngine(SF);
  const analyst = makeEngine(SF);
  await player.init();
  await analyst.init();
  analyst.send('setoption name Threads value 2');

  const puzzles = [];
  const seen = new Set();
  let gameNo = 0;

  while (puzzles.length < TARGET && gameNo < 60) {
    gameNo++;
    const game = new Chess();
    // randomised opening so games diverge
    const openingPlies = 2 + Math.floor(Math.random() * 6);
    for (let i = 0; i < openingPlies && !game.isGameOver(); i++) {
      const ms = game.moves({ verbose: true });
      game.move(ms[Math.floor(Math.random() * ms.length)]);
    }
    const skill = 1 + Math.floor(Math.random() * 5); // weak -> blunders

    for (let ply = 0; ply < 60 && !game.isGameOver(); ply++) {
      // analyse the current position for a tactic before the weak engine moves
      const fen = game.fen();
      const pieceCount = fen.split(' ')[0].replace(/[^a-zA-Z]/g, '').length;
      if (pieceCount >= 10 && !game.isCheck()) {
        const { lines } = await search(analyst, fen, { movetime: 450, multipv: 2 });
        const m1 = lines.get(1);
        const m2 = lines.get(2);
        if (isTactic(m1, m2)) {
          const key = fen.split(' ').slice(0, 2).join(' ');
          if (!seen.has(key)) {
            seen.add(key);
            const probe = new Chess(fen);
            const solMoves = [];
            for (const u of m1.pv.slice(0, 6)) {
              const mv = probe.move({ from: u.slice(0, 2), to: u.slice(2, 4), promotion: u[4] });
              if (!mv) break;
              solMoves.push(u);
            }
            puzzles.push({
              id: `t${puzzles.length + 1}`,
              fen,
              solution: solMoves,
              theme: classify(m1),
              turn: fen.split(' ')[1] === 'w' ? 'white' : 'black',
            });
            writeOut(puzzles); // incremental: partial results survive interruption
            process.stdout.write(`  found ${puzzles.length}/${TARGET} (${classify(m1)})\n`);
            if (puzzles.length >= TARGET) break;
          }
        }
      }
      // weak engine makes a (possibly bad) move
      const { best } = await search(player, fen, { movetime: 80, skill });
      if (!best || best === '(none)') break;
      game.move({ from: best.slice(0, 2), to: best.slice(2, 4), promotion: best[4] });
    }
  }

  player.kill();
  analyst.kill();
  writeOut(puzzles);
  console.log(`\nWrote ${puzzles.length} puzzles to apps/web/src/trainers/tactics.ts`);
}

main();
